id: I7C9D589C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:46:37+00:00'
last_modified: '2022-06-08T16:11:56.184424+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19123
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་འཁལ་འཐག་ལག་རྩལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0A00:
      image_group_id: I8LS19125
      title: ''
      total_pages: 52
      order: 1
      base_file: 0A00.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
